version: "3.9"
services:
  web_api:
    image: test  
    depends_on: 
        - "redis"
    container_name: api
    ports:
      - "4545:80"
    links:
       - "redis"
    build:
       context: .
       dockerfile: ./Dockerfile  
  sql:
     image: "mcr.microsoft.com/mssql/server:2019-latest"
     container_name: mssql
     ports:
      - "1433:1433" 
     environment:
      - ACCEPT_EULA=y
      - MSSQL_SA_PASSWORD=root.ROOT
     volumes:
      - sql_data:/var/opt/mssql

  redis:
    image: redis
    container_name: cache
    ports:
        - "6379:6379"

volumes:
   sql_data:
